id: P49376CF5
initial_creation_type: input
source_metadata:
  title: Sakya Paṇḍita Series
  language: en
  description: 'A series of texts by and about the great scholar Sakya Paṇḍita Kunga
    Gyaltsen (kun dga'' rgyal mtshan, 1182–1251):'
  volume:
    9814c4c5fd154124b34cdbcf112ac4f8:
      title: A Wondrous Instruction for the Moment of Death
      parent: Advice
    e2d45964de6b489ab7ea76bed1992ce0:
      title: Meditation on Amitābha
      parent: Advice
    880344a9747c40df86a26bb100e65f89:
      title: Verses of Aspiration to Recite While Prostrating
      parent: Aspiration Prayers
    943209becce84394ac65e57efd5ab18a:
      title: The Gaṇacakra Ritual
      parent: Commentaries
    aee04db9c9104fc3905bbb24dd9e6914:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    20f5f98748ea46629e493ab2c7c850c2:
      title: 'The Sun of Ambrosial Wisdom: A Guru Yoga of Dharmarāja Sakya Paṇḍita'
      parent: Guru Yoga
    100694e81398491abd3ee970f8f98534:
      title: Sakya Paṇḍita’s Instruction on Parting from the Four Attachments
      parent: Mind Training
    c47e354d16c14edaa1b0c4fa36e4c7df:
      title: Praise to Sakya Paṇḍita
      parent: Praise
    bb5224c8e9a04b7ab7f0d59bf630eba0:
      title: Prayer to Invoke the Wisdom Mind of the Gentle Protector Sakya Paṇḍita
      parent: Prayers
created_at: '2022-03-01T01:26:41.730240'
last_modified_at: '2022-03-01T01:26:41.730246'
